"""Regenerates `src/_protocol_versions.py` from the installed `heroprotocol`
package. Run this after bumping the `heroprotocol` dependency in
pyproject.toml, from the repo root:

    pip install -e daemon-python
    python daemon-python/assets/generate_protocol_manifest.py

`heroprotocol.versions.list_all()`/`.latest()` pick a protocol build by
listing files next to their own `__file__` at runtime -- fine for a normal
install, but Nuitka's `--onefile` build doesn't put those `.py` files on
disk at that path (only `parser.py`'s `importlib.import_module` calls do,
since those go through Nuitka's compiled-module registry instead of the
filesystem). See `src/_protocol_versions.py` and `parser.py`'s
`_build_protocol` for the runtime side of this.
"""

from __future__ import annotations

import re
from pathlib import Path

from heroprotocol.versions import list_all

_MODULE_OUT = Path(__file__).resolve().parent.parent / "src" / "_protocol_versions.py"
_FILENAME_RE = re.compile(r"protocol(\d+)\.py")


def main() -> None:
    builds = sorted(int(_FILENAME_RE.match(name).group(1)) for name in list_all())
    if not builds:
        raise RuntimeError("heroprotocol.versions.list_all() returned no protocol files")

    wrapped = "\n    ".join(
        ", ".join(str(b) for b in builds[i : i + 10]) + ("," if i + 10 < len(builds) else ",")
        for i in range(0, len(builds), 10)
    )

    _MODULE_OUT.write_text(
        '"""Every protocol build number bundled by the installed `heroprotocol`\n'
        "package, generated by `assets/generate_protocol_manifest.py`. Regenerate\n"
        "after bumping the `heroprotocol` dependency in pyproject.toml.\n\n"
        "Embedded as a plain tuple rather than discovered at runtime (which is what\n"
        "`heroprotocol.versions.list_all()`/`.latest()` do, via `os.listdir` next to\n"
        "their own `__file__`) because that discovery breaks under Nuitka's\n"
        "`--onefile` packaging: the compiled `heroprotocol.versions` module's\n"
        "`__file__` resolves to a path under the app's onefile temp-extraction\n"
        "directory, but the actual `.py` sources were compiled into the executable\n"
        "rather than extracted there, so the directory doesn't exist on disk and\n"
        "`os.listdir` raises `FileNotFoundError`. `parser.py` instead imports a\n"
        "specific `heroprotocol.versions.protocolNNNNN` module by name via\n"
        "`importlib.import_module`, which Nuitka's compiled-module registry does\n"
        "resolve correctly (it's the same mechanism `--include-package=heroprotocol`\n"
        "relies on), and only needs this manifest to pick the newest build for\n"
        "generic replay-header decoding.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "KNOWN_PROTOCOL_BUILDS: tuple[int, ...] = (\n"
        f"    {wrapped}\n"
        ")\n",
        encoding="utf-8",
    )
    print(f"wrote {_MODULE_OUT} ({len(builds)} builds, latest {builds[-1]})")


if __name__ == "__main__":
    main()
