#!/usr/bin/env bun
/**
 * Ensures a local Postgres is up (via docker-compose.dev.yml) and a
 * `hots_stats_test` database exists, migrated and seeded (maps + heroes),
 * writing `.env.test` if it doesn't already exist. Idempotent -- safe to
 * run before every `bun run test:api` invocation, including on a fresh
 * checkout. See docs/superpowers/specs/2026-08-31-dev-test-environment-design.md.
 */
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { $ } from "bun";

const TEST_DB_NAME = "hots_stats_test";
const PG_USER = process.env.POSTGRES_USER ?? "postgres";
const PG_PASSWORD = process.env.POSTGRES_PASSWORD ?? "postgres";
const TEST_DATABASE_URL = `postgres://${PG_USER}:${PG_PASSWORD}@localhost:5432/${TEST_DB_NAME}`;
const ENV_TEST_PATH = join(import.meta.dir, "..", ".env.test");

async function ensureDockerUp(): Promise<void> {
  await $`docker compose -f docker-compose.dev.yml up -d`;

  for (let attempt = 1; attempt <= 20; attempt++) {
    const result = await $`docker compose -f docker-compose.dev.yml exec -T postgres pg_isready -U ${PG_USER}`
      .nothrow()
      .quiet();
    if (result.exitCode === 0) return;
    await Bun.sleep(500);
  }
  throw new Error("Postgres did not become ready within 10s of `docker compose up`.");
}

async function ensureTestDatabase(): Promise<void> {
  const postgres = (await import("postgres")).default;
  const maint = postgres(`postgres://${PG_USER}:${PG_PASSWORD}@localhost:5432/postgres`, { max: 1 });
  try {
    const [{ exists }] =
      await maint`SELECT EXISTS (SELECT FROM pg_database WHERE datname = ${TEST_DB_NAME}) AS exists`;
    if (!exists) {
      await maint.unsafe(`CREATE DATABASE ${TEST_DB_NAME}`);
      console.log(`Created database ${TEST_DB_NAME}`);
    }
  } finally {
    await maint.end();
  }
}

function ensureEnvTestFile(): void {
  if (existsSync(ENV_TEST_PATH)) return;
  writeFileSync(
    ENV_TEST_PATH,
    "# Generated by scripts/test-db-up.ts -- local only, gitignored (see .gitignore's .env.* pattern).\n" +
      `DATABASE_URL=${TEST_DATABASE_URL}\n`,
  );
  console.log(`Wrote ${ENV_TEST_PATH}`);
}

async function migrateAndSeed(): Promise<void> {
  const env = { ...process.env, DATABASE_URL: TEST_DATABASE_URL };
  await $`bun run packages/db/src/migrate.ts`.env(env);
  await $`bun run packages/db/src/seed.ts`.env(env);
}

await ensureDockerUp();
await ensureTestDatabase();
ensureEnvTestFile();
await migrateAndSeed();
console.log(`Test database ready: ${TEST_DATABASE_URL}`);
